### PR TITLE
Allow for multiple headers

### PR DESCRIPTION
**Pull request by hadichaudhri**
To summarize the difference between `insert_header` and `append_header`, we must look at two cases:
1. No headers pre-established
    - Both methods will add the respective headers to the request
2. Headers pre-established
    - `insert_header` will overwrite the previous headers with those that are specified
    - `append_header` will add the specified headers in addition to those that were previously added
    For example, if there was already a header "foo: bar":
             `insert_header("ham", "spam")` would result in the header being "ham: spam", while `append_header("ham", "spam")` would result in two header values, "foo: bar" and "ham: spam".

TODO: See if this patch is applicable to  witter/backend/src/middlewares.rs as well.

### CODE REVIEW

**Comment by therealchaudhri** [comment]
This is my take on it, correct me if I'm mistaken :)

**Comment by davidpdrsn** [comment]
Yeah it seems you're right. Honestly kinda confusing. When would I want to insert a header and remove all other headers?

It seems there are some conflicts. Would you mind fixing them? Then I'll go a head and merge 😊

**Comment by therealchaudhri** [comment]
Yay, build passing! Ideally I would like to add a test for the introduced functionality, but I'm a bit new to Rust and frankly don't even know under which test file this would be categorized.

**Comment by therealchaudhri** [comment]
Note for future reference:

This
> TODO: See if this patch is applicable to witter/backend/src/middlewares.rs as well.
will not be necessary if #14 allows us to remove our implementation of `CorsMiddleware` in favor of the upstream version, as `ErrorResponseToJson` does not deal with headers. I don't see any reason to deal with headers anyway, as any header-setting can be managed through the layering of more middlewares, as we have done with `CorsMiddleware` :).

**Comment by davidpdrsn** [comment]
Thanks!

**Pull request merged**
