### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by amcsi**
This is kind of cause I want to see if when I would make a tiny improvement on this project, I could see if the tests would pass. Cause I'm too lazy to install Postgres on my local machine :D

CI passes: https://travis-ci.org/github/amcsi/witter

### CODE REVIEW

**Comment by amcsi** [comment]
The tests seem to fail when SECRET_KEY is not set by the way, so you might want to enforce it to be set.

**Comment by davidpdrsn** [comment]
Thanks! However I've recently been trying GitHub Actions and I'm very happy with it. I haven't set it up for a project that uses postgres though. Was thinking I would like to do that here.

**Comment by amcsi** [comment]
@davidpdrsn feel free to close it if you'd be using something else... though might I suggest that in the meantime you could merge and use this; and then when you finish writing the Github actions code, you could remove this `.travis.yml`. Cause you'd get green ticks and red x's until then

**Comment by davidpdrsn** [comment]
Sure thats a good point 👍

**Pull request merged**
